### ISSUE TITLE
LUA Error on Player Reports

### ISSUE THREAD

**Issue by 1Botnet** [0xbs/premade-groups-filter#96] opened 2022-07-30 00:57 UTC
https://i.imgur.com/1k0ojRv.png

This happens when reporting advertising etc within LFG.

**Comment by 0xbs** [comment] 2022-07-30 07:28
Thanks for the report, but it is a duplicate of the previous issue #95 and cannot be fixed at the moment.

**Closed** 2022-07-30 07:28 UTC
