### ISSUE TITLE
Wrath Classic 5.0.0-beta client crash

### ISSUE THREAD

**Issue by Road-block** [0xbs/premade-groups-filter#217] opened 2023-11-04 23:44 UTC
Please check (replace the space in the brackets with an x like this `- [x] ...`):
- [x]  I read the FAQ:  https://github.com/0xbs/premade-groups-filter/wiki/FAQ
- [x]  I searched for existing issues:  https://github.com/0xbs/premade-groups-filter/issues?q=

### Game Version
Wrath Classic 3.4.3

### Lua error from Bugsack
So this is hard to debug.
Version 5.0.0-beta (upgrade from 4.3.1-beta-wrath, so not a clean install, some saved variables would be present)

### Screenshots
Screenshots are extremely helpful. Drag your screenshot files here (do not paste). Full un-cropped screenshots are preferred.

### Current behavior
After installing version 5.0.0-beta trying to load the game crashes my client at the end of the loading bar.
A hard crash (assertion failure)
I can't get into the game to see if there are some Lua errors, but I isolated it to this addon by doing a binary search (enable / disable addons for different characters, until I found the one crashing me)
Previous beta for wrath 4.3.1-beta was used for about a week without issue, so something in the new version (or the combination of new version + old saved variables) is crashing my wow client.

### Steps to reproduce
1. Open premade dungeon list
2. Setup filters ...
3. Click on ...

### Expected behavior
Describe what you expect to happen.

**Comment by Road-block** [comment] 2023-11-05 00:27
Going to close it for now, can't find a 100% repro case.

**Comment by 0xbs** [comment] 2023-11-05 06:35
I will test again and see if I can change something. I hooked a new function on startup, so maybe that is causing problems. Saved state did not change.

I suspect a timing issue in this case, maybe something did load faster/slower than expected.

On my Wrath client with only PFF, BugSack and BugGrabber installed the addon works fine at the moment.

**Comment by 0xbs** [comment] 2023-11-05 09:26
I did some more tests but could not reproduce your errors. Let's hope it was just a hiccup.

**Comment by Road-block** [comment] 2023-11-05 18:46
Well this sucks. It happens when I'm in a raid, size doesn't seem to matter, I had someone help me group with an alt.

**Comment by 0xbs** [comment] 2023-11-05 21:08
So you're in a raid and search for a group? Could you describe the steps to reproduce the error?

And BugGrabber/BugSack does not show anything?

**Comment by Road-block** [comment] 2023-11-05 21:17
So when this happens, I'm not listed in LFG tool, it seems to happen on roster updates and when it does it's a hard client crash, BugGrabber/BugSack is clean until it does. When it happens in the loading screen I'm not yet in-game to see if there's some error.

This is a kind of issue that's so annoying, I've had it happen in the past and it's hard to be 100% it's *this* addon or what exactly causes it.

 “Error message #138 Exemption: Access_Violation" it crashes the wow client.
Anyway, I'll try to run without PGF for a few days, if it happens again your addon might be unrelated, in that case apologies in advance 😄

**Comment by 0xbs** [comment] 2023-11-19 21:23
As other players are not reporting any issues, I suspect a problem with your client or computer and will close this issue.

**Closed by 0xbs** 2023-11-19 21:23 UTC
Labels: bug
