### ISSUE TITLE
SendReport() Error

### ISSUE THREAD

**Issue by ljlevend** [0xbs/premade-groups-filter#134] opened 2022-12-23 19:19 UTC
I get this error when I right click a group and select "Report Advertisement":

Message: [ADDON_ACTION_FORBIDDEN] AddOn 'PremadeGroupsFilter' tried to call the protected function 'SendReport()'.
Time: Fri Dec 23 13:14:33 2022
Count: 1
Stack: [ADDON_ACTION_FORBIDDEN] AddOn 'PremadeGroupsFilter' tried to call the protected function 'SendReport()'.
[string "@Interface/FrameXML/ReportFrame.lua"]:79: in function `InitiateReportInternal'
[string "@Interface/FrameXML/ReportFrame.lua"]:432: in function <Interface/FrameXML/ReportFrame.lua:418>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/ReportFrame.lua"]:56: in function `InitiateReport'
[string "@Interface/FrameXML/LFGList.lua"]:3260: in function `LFGList_ReportAdvertisement'
[string "@Interface/FrameXML/LFGList.lua"]:3292: in function `func'
[string "@Interface/SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>

Locals: <none>

**Comment by 0xbs** [comment] 2022-12-23 20:26
Thank you for your report. It's however a duplicate of #95

**Closed** 2022-12-23 20:27 UTC
