### ISSUE TITLE
BugSack swears very hard.

### ISSUE THREAD

**Issue by Hollicsh** [0xbs/premade-groups-filter#73] opened 2021-12-28 01:11 UTC
1x PremadeGroupsFilter\Dialog\Dialog.lua:52: attempt to index local 'model' (a nil value)
[string "@PremadeGroupsFilter\Dialog\Dialog.lua"]:52: in function <PremadeGroupsFilter\Dialog\Dialog.lua:49>

Locals:
self = UsePFGButton {
 0 = <userdata>
 isSkinned = true
 SetHighlightTexture = <function> defined =[C]:-1
 SetPushedTexture = <function> defined =[C]:-1
 text = UsePFGButtonText {
 }
 Backdrop = <unnamed> {
 }
 SetNormalTexture = <function> defined =[C]:-1
}
button = "LeftButton"
down = false
checked = true
model = nil
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to index local 'model' (a nil value)"
PGF = <table> {
 PopupMenu_Toggle = <function> defined @PremadeGroupsFilter\Dialog\PopupMenu.lua:126
 GetModel = <function> defined @PremadeGroupsFilter\Main.lua:77
 Dialog_ResetPosition = <function> defined =[C]:-1
 Dialog_SetUpMinMaxField = <function> defined @PremadeGroupsFilter\Dialog\Setup.lua:175
 GameTooltip_AddWhite = <function> defined @PremadeGroupsFilter\Dialog\Help.lua:25
 ResetSearchEntries = <function> defined @PremadeGroupsFilter\Main.lua:114
 previousSearchExpression = ""
 GetLockoutInfo = <function> defined @PremadeGroupsFilter\Modules\Lockout.lua:52
 Empty = <function> defined @PremadeGroupsFilter\Modules\Util.lua:102
 Table_Copy_Shallow = <function> defined @PremadeGroupsFilter\Modules\Util.lua:36
 Table_Subtract = <function> defined @PremadeGroupsFilter\Modules\Util.lua:57
 declinedGroups = <table> {
 }
 DoesPassThroughFilter = <function> defined @PremadeGroupsFilter\Modules\Expression.lua:46
 previousSearchLeaders = <table> {
 }
 HasRemainingSlotsForLocalPlayerPartyRoles = <function> defined @PremadeGroupsFilter\Main.lua:136
 Dialog_Reset = <function> defined @PremadeGroupsFilter\Dialog\Dialog.lua:121
 DoFilterSearchResults = <function> defined @PremadeGroupsFilter\Main.lua:283
 Dialog_OnMouseUp = <function> defined @PremadeGroupsFilter\Dialog\Setup.lua:72
 RemoveCommentLines = <function> defined @PremadeGroupsFilter\Main.lua:67
 GetDifficulty = <function> defined @PremadeGroupsFilter\Modules\Difficulty.lua:320
 UsePFGButton = UsePFGButton {
 }
 ACTIVITY_TO_DIFFICULTY = <table> {
 }
 currentSearchExpression = "true"
 Dialog_MaximizeButton_OnClick = <function> defined @PremadeGroupsFilter\Dialog\Setup.lua:82
 IsDeclinedGroup = <function> defined @PremadeGroupsFilter\Main.lua:502
 Dialog_MinimizeButton_OnClick = <function> defined @PremadeGroupsFilter\Dialog\Setup.lua:76
 Popup_GetSelectedEntry = <function> defined @PremadeGroupsFilter\Dialog\PopupMenu.lua:130
 Dialog_SetUpUsePGFCheckbox = <function> defined @PremadeGroupsFilter\Dialog\Setup.lua:186
 GetMatchingBossInfo = <function> defined @PremadeGroupsFilter\Modules\Lockout.lua:80
 PopupMenu_Hide = <function> defined @PremadeGroupsFilter\Dialog\PopupMenu.lua:121
 GameTooltip_AddDoubleWhite = <function> defined @PremadeGroupsFilter\Dialog\Help.lua:29
 Dialog_OnModelUpdate = <function> defined @PremadeGroupsFilter\Dialog\Dialog.lua:42
 Dialog_Max_OnTabPressed = <function> defined @PremadeGroupsFilter\Dialog\Dialog.lua:166
 OnLFGListSearchEntryOnEnter = <function> defined @PremadeGroupsFilter\Main.lua:552
 NotEmpty = <function> defined @PremadeGroupsFilter\Modules\Util.lua:101
 Dialog_Toggle = <function> defined @PremadeGroupsFilter\Dialog\Dialog.lua:171
 SHORTNAME_TO_DIFFICULTY = <table> {
 }
 Dialog_Min_OnTabPressed = <function> defined @PremadeGroupsFilter\Dialog\Dialog.lua:162
 currentSearchLeaders = <table> {
 }
 Dialog_DifficultyDropdown_OnClick = <function> defined @PremadeGroupsFilter\Dialog\Dialog.lua:151
 Dialog_ResetButton_OnClick = <function> defined @PremadeGroupsFilter\Dialog\Dialog.lua:145
 Dialog_RefreshButton_OnClick = <function> defined @PremadeGroupsFilter\Dialog\Dialog.l
 
 
 
 
 
 
 I heard that the problem is with the Project Azilroka addon.
Azil claims the problem is with the PGF addon.

Azilroka — Today, in 6:02
looks like a problem with their addon

**Comment by 0xbs** [comment] 2021-12-28 09:59
Duplicate of #53, let's continue the discussion there.

**Closed by 0xbs** 2021-12-28 09:59 UTC
