### ISSUE TITLE
Groups alwys doubled

### ISSUE THREAD

**Issue by Sheps30** [0xbs/premade-groups-filter#79] opened 2022-03-06 09:18 UTC
![image](https://user-images.githubusercontent.com/43088242/156916870-0124829f-3781-45fa-b242-c2d57fb7a115.png)

**Comment by 0xbs** [comment] 2022-03-06 10:07
I am seeing the same behavior if I disable all addons, so this cannot be an issue with Premade Groups Filter.

Steps to reproduce: I logged into my toon, all addons disabled. I signed up for a group. At first, it shows only one green group listing. If I click the reload button, I suddenly see a duplicate of the group I just signed up.

**Comment by 0xbs** [comment] 2022-03-06 10:22
I just found the bug on Stanzilla/WoWUIBugs#224 and there are also posts in the US forums pointing out this issue. This is a Blizzard bug. There is also a small code snipped you can paste into any addon lua file to temporarily fix the problem.

**Closed by 0xbs** 2022-03-06 10:22 UTC

**Comment by Milky063** [comment] 2022-04-18 20:23
Where exactly do we post this "small code snipped"?

**Comment by 0xbs** [comment] 2022-04-18 20:26
Just at the end of any lua file of any addon, e.g. Main.lua of PGF.

**Comment by Milky063** [comment] 2022-04-18 20:29
Appreciate it. Hope it works.
